name: testges
description: Application de signature GeSign

publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.1+6

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^1.0.0
  path_provider: ^2.0.11
  http: ^1.2.1
  pull_to_refresh: ^2.0.0
  intl: '>=0.18.1 <0.20.0'
  syncfusion_flutter_calendar: ^26.1.37
  table_calendar: ^3.0.0
  file_picker: 8.0.6
  web_socket_channel: ^3.0.0
  jwt_decoder: ^2.0.1
  qr_code_scanner: ^1.0.1
  confetti : ^0.7.0
  shared_preferences: ^2.0.6
  mime: ^1.0.0
  cloudinary_flutter: ^1.3.0
  cloudinary_url_gen: ^1.5.0
  permission_handler: ^10.2.0
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.0

flutter:
  uses-material-design: true

  assets:
    - assets/
